# Generated by Django 3.1.4 on 2021-01-15 05:31

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('sendersy', '0002_auto_20210115_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=None, null=True, verbose_name=time.localtime),
        ),
    ]
