# Generated by Django 3.1.4 on 2021-01-15 05:32

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('sendersy', '0003_auto_20210115_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(null=True, verbose_name=time.localtime),
        ),
    ]
