# Generated by Django 3.1.4 on 2021-01-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendersy', '0005_auto_20210115_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=(2021, 1, 15, 11, 5, 11, 4, 15, 0), null=True),
        ),
    ]
