# Generated by Django 3.1.4 on 2021-01-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendersy', '0006_auto_20210115_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default='11:14:27'),
        ),
    ]
