# Generated by Django 3.1.4 on 2021-01-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendersy', '0011_auto_20210115_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
